sudo: required
services:
  - docker

before_install:
  - docker build -t michaelsu/multi-container-app -f ./client/Dockerfile.dev ./client

script:
  - docker run michaelsu/multi-container-app npm test -- --coverage

after_success:
  # The name before / has to be the docker id.
  - docker build -t michaelsu/multi-container-app-client ./client
  - docker build -t michaelsu/multi-container-app-nginx ./nginx
  - docker build -t michaelsu/multi-container-app-server ./server
  - docker build -t michaelsu/multi-container-app-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  # docker push yourhubusername/verse_gapminder
  - docker push michaelsu/multi-container-app-client
  - docker push michaelsu/multi-container-app-nginx
  - docker push michaelsu/multi-container-app-server
  - docker push michaelsu/multi-container-app-worker

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
